substitutions:
  _COMMIT_ID: {{ commitId }}
  _BRANCH_NAME: {{ branchName }}

options:
  substitution_option: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/git'
    id: 'Clone intelligent pipeline'
    entrypoint: 'bash'
    args: [
      '-c',
      'git clone https://github.com/brianpipeline/intelligent-pipeline'
    ]

  - name: 'gcr.io/cloud-builders/git'
    id: 'Clone repo'
    entrypoint: 'bash'
    args: [
      '-c',
      'git clone {{ cloneUrl }}'
    ]

  - name: 'gcr.io/cloud-builders/git'
    id: 'Clone repo'
    entrypoint: 'bash'
    args: 
      - '-eEuo'
      - 'pipefail'
      - '-c'
      - |-
        if [ "$_COMMIT_ID" == "" ]
        then
          cd {{ repoName }} && git checkout $_BRANCH_NAME
        else
          cd {{ repoName }} && git checkout $_COMMIT_ID
        fi

  - name: 'gcr.io/cloud-builders/git'
    id: 'REMOVE - test branch status'
    entrypoint: 'bash'
    args: [
      '-c',
      'cd {{ repoName }} && git status'
    ]

  - name: '{{buildImage}}'
    id: 'build project'
    entrypoint: 'bash'
    args: [
      "-c",
      "cd {{ repoName }} && {{ buildArgs }}"
    ]

  - name: 'node:16'
    id: 'run generateArtifactPush'
    entrypoint: 'bash'
    args: 
      - '-eEuo'
      - 'pipefail'
      - '-c'
      - |-
        if [ "$_BRANCH_NAME" == "main" ] || ["$_BRANCH_NAME" == *"release"*]
        then
          echo "hey"
        else
          echo "yooo"
        fi