substitutions:
  _BRANCH_NAME: {{ branchName }}

options:
  substitution_option: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/git'
    id: 'Clone intelligent pipeline'
    entrypoint: 'bash'
    args: [
      '-c',
      'git clone https://github.com/brianpipeline/intelligent-pipeline'
    ]

  - name: 'gcr.io/cloud-builders/git'
    id: 'Clone repo'
    entrypoint: 'bash'
    args: [
      '-c',
      'git clone {{ cloneUrl }} && cd {{ repoName }} && git checkout $_BRANCH_NAME'
    ]

  - name: 'gcr.io/cloud-builders/git'
    id: 'REMOVE - test branch status'
    entrypoint: 'bash'
    args: [
      '-c',
      'cd {{ repoName }} && git status'
    ]

  - name: '{{buildImage}}'
    id: 'build project'
    entrypoint: 'bash'
    args: [
      "-c",
      "cd {{ repoName }} && {{ buildArgs }}"
    ]
  {{#ifIsMainOrRelease branchName}}
  {{/ifIsMainOrRelease}}
