substitutions:
  _COMMIT_ID: {{ commitId }}
  _BRANCH_NAME: {{ branchName }}

options:
  substitution_option: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/git'
    id: 'Clone intelligent pipeline'
    entrypoint: 'bash'
    args: [
      '-c',
      'git clone https://github.com/brianpipeline/intelligent-pipeline'
    ]

  - name: 'gcr.io/cloud-builders/git'
    id: 'Clone repo'
    entrypoint: 'bash'
    args: [
      '-c',
      'git clone {{ cloneUrl }}'
    ]

  - name: 'gcr.io/cloud-builders/git'
    id: 'Checkout stuff'
    entrypoint: 'bash'
    args: 
      - '-eEuo'
      - 'pipefail'
      - '-c'
      - |-
        if [ "$_COMMIT_ID" == "" ]
        then
          cd {{ repoName }} && git checkout $_BRANCH_NAME
        else
          cd {{ repoName }} && git checkout $_COMMIT_ID
        fi

  - name: 'gcr.io/cloud-builders/git'
    id: 'REMOVE - test branch status'
    entrypoint: 'bash'
    args: [
      '-c',
      'cd {{ repoName }} && git status'
    ]

  - name: '{{buildImage}}'
    id: 'build project'
    entrypoint: 'bash'
    args: [
      "-c",
      "cd {{ repoName }} && {{ buildArgs }}"
    ]

  - name: 'node:16'
    id: 'run generateArtifactPush'
    entrypoint: 'bash'
    args: 
      - '-eEuo'
      - 'pipefail'
      - '-c'
      - |-
        if [[ "$_BRANCH_NAME" == *"release"* ]] || [[ "$_BRANCH_NAME" == "main" ]]
        then
          cd intelligent-pipeline/cloudbuild_generator \
          && npm install \
          && node generateArtifactPush.js \
          /workspace/{{ repoName }}/brianpipeline.yaml  \
          templates/cloudbuild-artifactpush-template.yaml \
          $_BRANCH_NAME \
          {{ repoName }} \
          {{ cloneUrl }} \
          $_COMMIT_ID \
          /workspace/{{ repoName }}/build.gradle \
          /workspace/{{ repoName }}/settings.gradle
        else
          echo "Not cascading - this is a feature branch."
        fi
  
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Create new pubsub topic.'
    entrypoint: 'bash'
    args:
      - '-eEuo'
      - 'pipefail'
      - '-c'
      - |-
        if [[ "$_BRANCH_NAME" == *"release"* ]] || [[ "$_BRANCH_NAME" == "main" ]]
        then
          if [[ -z "$(gcloud pubsub topics describe {{ repoName }}-artifact-push 2>&1 >/dev/null)" ]]; 
          then
            echo "Pubsub topic already exists"
          else
            gcloud pubsub topics create {{ repoName }}-artifact-push
          fi
        else
          echo "Not cascading - this is a feature branch."
        fi
  

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Create artifact push pipeline.'
    entrypoint: 'bash'
    args:
      - '-eEuo'
      - 'pipefail'
      - '-c'
      - |-
        if [[ "$_BRANCH_NAME" == *"release"* ]] || [[ "$_BRANCH_NAME" == "main" ]]
          if [[ -z "$(gcloud builds triggers describe {{ repoName }}-artifact-push 2>&1 >/dev/null)" ]]; 
          then
            gcloud builds triggers delete {{ repoName }}-artifact-push
            gcloud builds triggers create pubsub \
            --name={{ repoName }}-artifact-push \
            --topic=projects/cloud-build-pipeline-396819/topics/{{ repoName }}-artifact-push \
            --inline-config=/workspace/cloudbuild_generator/cloudbuild-artifactpush.yaml \
            --substitutions=_COMMIT_ID=$_COMMIT_ID,_BRANCH_NAME=$(echo $_BRANCH_REF | sed 's/refs\/heads\///') \
            --region=global
          else
            gcloud builds triggers create pubsub \
            --name={{ repoName }}-artifact-push \
            --topic=projects/cloud-build-pipeline-396819/topics/{{ repoName }}-artifact-push \
            --inline-config=/workspace/cloudbuild_generator/cloudbuild-artifactpush.yaml \
            --substitutions=_COMMIT_ID=$_COMMIT_ID,_BRANCH_NAME=$(echo $_BRANCH_REF | sed 's/refs\/heads\///') \
            --region=global
          fi
        else
          echo "Not cascading - this is a feature branch."
        fi

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Publish pubsub message'
    entrypoint: 'bash'
    args:
      - '-eEuo'
      - 'pipefail'
      - '-c'
      - |-
        if [[ "$_BRANCH_NAME" == *"release"* ]] || [[ "$_BRANCH_NAME" == "main" ]]
        then
          gcloud pubsub topics publish projects/cloud-build-pipeline-396819/topics/{{ repoName }}-artifact-build \
          --message='{"unused": "{{ repoName }}"}'
        else
          echo "Not cascading - this is a feature branch."
        fi