substitutions:
  # Repository Specific configuration. DevOps can change these as needed
  _REPOSITORY_NAME: $(body.repository.name)
  _REPO_TO_CLONE: $(body.repository.clone_url)
  _BRANCH_NAME: $(body.ref)
  _COMMIT_ID: $(body.head_commit.id)
  _SHORT_BUILD_ID: ${BUILD_ID:0:8}

options:
  substitution_option: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'ubuntu'
    id: 'Print results'
    entrypoint: 'bash'
    args: [
      '-c',
      'echo $_REPOSITORY_NAME'
    ]

  - name: 'gcr.io/cloud-builders/git'
    id: 'Clone intelligent pipeline'
    entrypoint: 'bash'
    args: [
      '-c',
      'git clone https://github.com/brianpipeline/intelligent-pipeline'
    ]

  - name: 'gcr.io/cloud-builders/git'
    id: 'Clone webhook repo'
    entrypoint: 'bash'
    args: [
      '-c',
      'git clone $_REPO_TO_CLONE'
    ]

  - name: 'node:16'
    id: 'run generateCloudBuild'
    entrypoint: 'bash'
    args: [
      '-c',
      'cd cloudbuild_generator 
      && npm install 
      && node generateArtifactBuild.js 
      /workspace/$_REPOSITORY_NAME/brianpipeline.yaml 
      /workspace/cloudbuild_generator/templates/cloudbuild-artifactbuild-template.yaml 
      $_BRANCH_NAME
      $_REPOSITORY_NAME
      $_REPO_TO_CLONE'
    ]

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Create new pubsub topic.'
    entrypoint: 'bash'
    args:
      - '-eEuo'
      - 'pipefail'
      - '-c'
      - |-
        if [[ -z "$(gcloud pubsub topics describe $_REPOSITORY_NAME-artifact-build 2>&1 >/dev/null)" ]]; 
        then
          echo "Pubsub topic already exists"
        else
          gcloud pubsub topics create $_REPOSITORY_NAME-artifact-build
        fi

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Create or update pubsub trigger.'
    entrypoint: 'bash'
    args:
      - '-eEuo'
      - 'pipefail'
      - '-c'
      - |-
        if [[ -z "$(gcloud builds triggers describe $_REPOSITORY_NAME-artifact-build 2>&1 >/dev/null)" ]]; 
        then
          gcloud builds triggers delete $_REPOSITORY_NAME-artifact-build
          gcloud builds triggers create pubsub \
          --name=$_REPOSITORY_NAME-artifact-build \
          --topic=projects/cloud-build-pipeline-396819/topics/$_REPOSITORY_NAME-artifact-build \
          --inline-config=/workspace/cloudbuild_generator/cloudbuild-artifactbuild.yaml \
          --substitutions=_BRANCH_NAME=$_COMMIT_ID \
          --region=global
        else
          gcloud builds triggers create pubsub \
          --name=$_REPOSITORY_NAME-artifact-build \
          --topic=projects/cloud-build-pipeline-396819/topics/$_REPOSITORY_NAME-artifact-build \
          --inline-config=/workspace/cloudbuild_generator/cloudbuild-artifactbuild.yaml \
          --substitutions=_BRANCH_NAME=$_COMMIT_ID \
          --region=global
        fi

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Publish pubsub message'
    entrypoint: 'bash'
    args:
      - '-eEuo'
      - 'pipefail'
      - '-c'
      - |-
        gcloud pubsub topics publish projects/cloud-build-pipeline-396819/topics/$_REPOSITORY_NAME-artifact-build \
        --message='{"unused": "$_REPOSITORY_NAME"}'