substitutions:
  # Repository Specific configuration. DevOps can change these as needed
  _REPOSITORY_NAME: $(body.repository.name)
  _REPO_TO_CLONE: $(body.repository.clone_url)

options:
  substitution_option: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'ubuntu'
    id: 'Print results'
    entrypoint: 'bash'
    args: [
      '-c',
      'echo $_REPOSITORY_NAME'
    ]

  - name: 'gcr.io/cloud-builders/git'
    id: 'Clone intelligent pipeline'
    entrypoint: 'bash'
    args: [
      '-c',
      'git clone https://github.com/brianpipeline/intelligent-pipeline'
    ]

  - name: 'gcr.io/cloud-builders/git'
    id: 'Clone webhook repo'
    entrypoint: 'bash'
    args: [
      '-c',
      'git clone $_REPO_TO_CLONE'
    ]

  - name: 'node:16'
    id: 'run generateCloudBuild'
    entrypoint: 'bash'
    args: [
      '-c',
      'cd cloudbuild_generator 
      && npm install 
      && node generateCloudBuild.js /workspace/$_REPOSITORY_NAME/brianpipeline.yaml /workspace/cloudbuild_generator/cloudbuild-template.yaml'
    ]

  - name: 'ubuntu'
    id: 'Do another ls'
    entrypoint: 'bash'
    args: [
      '-c',
      'cd cloudbuild_generator && ls'
    ]